package isolation

import (
	"errors"
	"testing"

	"github.com/golang/mock/gomock"
	// Ensure this matches your module name in go.mod
	"github.com/BugMentor/go-cloud-testing-demo/isolation/mocks"
)

func TestGetUserName(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	// Inject the Mock generated by gomock
	mockDB := mocks.NewMockDBClient(ctrl)
	service := UserService{Db: mockDB}

	// Scenario 1: Success
	mockDB.EXPECT().GetUser("123").Return("Matías", nil)

	result, err := service.GetUserName("123")
	if result != "User: Matías" || err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	// Scenario 2: Failure (Edge case)
	mockDB.EXPECT().GetUser("999").Return("", errors.New("DB error"))

	_, err = service.GetUserName("999")
	if err == nil {
		t.Error("Expected an error when DB fails")
	}
}
